### ISSUE TITLE
No Version Key Error

### ISSUE THREAD

**Issue by 556duckvader** [rsnodgrass/hass-poolmath#10]
Logger: homeassistant.loader
Source: loader.py:786 
First occurred: 11:17:27 AM (1 occurrences) 
Last logged: 11:17:27 AM

No 'version' key in the manifest file for custom integration 'poolmath'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'poolmath'

**Comment by rsnodgrass** [comment]
Not sure why this error is being reported.  The version key exists in manifest.json

https://github.com/rsnodgrass/hass-poolmath/blob/master/custom_components/poolmath/manifest.json

**Comment by 556duckvader** [comment]
I am not sure of that but I get that error log every time I restart the home assistant service.
