### ISSUE TITLE
sensors unavailable

### ISSUE THREAD

**Issue by cvonk** [rsnodgrass/hass-poolmath#14]
I have used this for a few months, but since core-2022.3.6 it get `unavailable` for the sensors.

![image](https://user-images.githubusercontent.com/9732506/160953797-1614eef0-6189-4a0a-b006-281046998a3a.png)

Running the `client.py` from a computer shows that it pulls the correct values from the web page.  However, they don't appear to update the sensor values.

thanks

**Comment by rsnodgrass** [comment]
Resolved in 0.2.0
