### ISSUE TITLE
What type of sensors

### ISSUE THREAD

**Issue by SerdarSanri** [rsnodgrass/hass-poolmath#2]
Just out of curiosity, what kind/type of sensors can be used in market to be able to automate this calculations. Maybe connecting to a esp module to feed homeassistant sensors. I looked up on ebay didn't see any module that can measure ph and other stuff bundled. Mostly handled tools for immediate tests.

**Comment by rsnodgrass** [comment]
Would love to know as well.  The only thing I found was pHin (
https://www.phin.com), which I own one, but it does't offer any API to
access the data.  If there was an alternative that provided APIs to read
data, I would switch to it immediately.  I'm waiting to see what Sutro
offers (https://mysutro.com/).
