### ISSUE TITLE
waterTemp sensor no longer available

### ISSUE THREAD

**Issue by nkm8** [rsnodgrass/hass-poolmath#22]
Previously, the `waterTemp` value was available as a temperature sensor in degrees F

**Comment by JonLaliberte** [comment]
Yeah I’m missing this as well.

**Comment by CrallH** [comment]
Yes my temp is gone to.

**Comment by rsnodgrass** [comment]
Just released 0.2.5 which now includes water temp, pressure, flow rate, and SWG cell percentage. I do not have these in my PoolMath setup, so this is untested. Let me know if this resolves the issues. NOTE: The sensor entity id *MAY* change from the previous entity id.

**Comment by JonLaliberte** [comment]
Temperature is working now. Entity ID did change.
