### ISSUE TITLE
F instead of C

### ISSUE THREAD

**Issue by CrallH** [rsnodgrass/hass-poolmath#23]
Hi!
My temp sensor displays as F in home assistant but as C in poolmath, is there a way i can change that in the component files?
![Screenshot_2023-05-21-10-40-11-866_com android chrome](https://github.com/rsnodgrass/hass-poolmath/assets/32394267/8d607492-18af-4491-a61b-986d7cf31d35)
![Screenshot_2023-05-21-10-39-19-870_io homeassistant companion android](https://github.com/rsnodgrass/hass-poolmath/assets/32394267/50529e0c-ce9d-440f-8f7e-6c2a72852575)

**Comment by rsnodgrass** [comment]
I believe you can change units in Home Assistant itself.

**Comment by CrallH** [comment]
> I believe you can change units in Home Assistant itself.

Yes that would be possible if the device_class is temperature, but it´s not, the sensors do not have any device class, so in that case i need to create a template sensor just to give it a device class and the correct unit. 

![image](https://github.com/rsnodgrass/hass-poolmath/assets/32394267/3e38f80b-010f-45af-a759-b4348bab07c5)

**Comment by CrallH** [comment]
I think i might have found a bug in poolmath app. All data is displayd in C in my app and in the JSON, but the     "waterTempUnitDefault" was 0. 
I unchecked the log temperature in the app and saved then reactivated it again. Now it´s     "waterTempUnitDefault": 1,
I saw that you used that in the code to set UnitOfTemperature.CELSIUS.

**Comment by CrallH** [comment]
after finding the issue in the JSON and fixing the update i now have correct unit.
![image](https://github.com/rsnodgrass/hass-poolmath/assets/32394267/c49e9943-67b3-484f-b70e-cf50fe972d7c)

**Comment by rsnodgrass** [comment]
Excellent!  Thanks for fixing the manifest issue too.
