### ISSUE TITLE
Error setting up platform after install

### ISSUE THREAD

**Issue by jmc2010** [rsnodgrass/hass-poolmath#3]
Thank you for putting together this integration for Home Assistant.  I'm looking forward to using it this season.   I added the integration through HACS, and added the YAML to the configuration, but am getting an error when I restart the server.   I checked the custom_components folder, and the file for Pool Math are there.  Here is the log entry:

```
Logger: homeassistant.components.sensor
Source: custom_components/poolmath/sensor.py:72
Integration: Sensor (documentation, issues)
First occurred: 10:31:18 PM (1 occurrences)
Last logged: 10:31:18 PM

Error while setting up poolmath platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/poolmath/sensor.py", line 50, in setup_platform
    client = PoolMathClient(config, add_entities)
  File "/config/custom_components/poolmath/sensor.py", line 72, in __init__
    pool_name = self._raw_data.select('h1')[0].string
IndexError: list index out of range
```

Not sure what I did wrong.  I did subscribe to the premium service, and received my custom URL which I used in the config.

Thanks, 

Jason

**Comment by rsnodgrass** [comment]
Jason, did you have a name for your pool defined on PoolMath?  It appears it cannot get the name of the pool for some reason.  I have updated the sensor with handling of a case where it cannot find a name for the pool and just released it. 

First try the updated hass-poolmath sensor (0.0.2) and see if that resolves your problem.  Then if that doesn't work, make sure you set a name for your pool on the Pool Math site.

**Comment by jmc2010** [comment]
I do have the pool named, at least in the android app.   I do see that the
24 hour SWG chlorine output isn't saving the input of .625.   Not sure if
that could be an issue.  I will try the update and see if that helps.

Thanks,

Jason

**Comment by jmc2010** [comment]
That did it!  Thank you for the help.  

Jason
