### ISSUE TITLE
Unknown Pool Math sensor 'bor' discovered at https://api.poolmathapp.com/share/XXXX

### ISSUE THREAD

**Issue by EmnaX** [rsnodgrass/hass-poolmath#7]
Hello,
Great work on this sensor! It's nice to see my pool values in HA now. I noticed in the log file that I am getting the following error:

`[custom_components.poolmath.sensor] Unknown Pool Math sensor 'bor' discovered at https://api.poolmathapp.com/share/XXXXX`

I have a pool and a hot tub in there and both report the same error.

Here are some details on my environment:
Pool Math Release: 0.0.4 using HACS
HACS: 1.6.0
System: HassOS 4.13  (armv7 / raspberrypi4)
Home Assistant: 0.115.2
Home Assistant Supervisor: 245

**Comment by rsnodgrass** [comment]
This may be Borates? Do you log those?

**Comment by rsnodgrass** [comment]
I believe this is indeed Borates, I've updated the sensor list in 0.0.5.  If you update, this should resolve the log message and a Borate sensor will be created.

**Comment by EmnaX** [comment]
Hi @rsnodgrass, 
Yes, it is indeed borates.

Wow, already fixed and closed, thanks!
